ALTER TABLE memory_entity ADD COLUMN updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP;
UPDATE memory_entity SET updated_at = DATE_FORMAT(record_at, "%Y-%m-%d %H:%i:%s") WHERE updated_at IS NULL;
ALTER TABLE memory_entity MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;