FROM amazoncorretto:21

WORKDIR /app

COPY module-batch/build/libs/module-batch.jar /app/swimie-batch.jar

CMD ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=batch", "swimie-batch.jar"]
