FROM amazoncorretto:21

WORKDIR /app

COPY module-presentation/build/libs/module-presentation.jar /app/appu.jar

CMD ["java", "-Djava.net.preferIPv4Stack=true", "-Duser.timezone=Asia/Seoul", "-Dspring.profiles.active=dev", "-jar", "appu.jar"]
