FROM amazoncorretto:21

WORKDIR /app

COPY module-batch/build/libs/module-batch.jar /app/batch-image.jar

CMD ["java", "-Djava.net.preferIPv4Stack=true", "-Duser.timezone=Asia/Seoul", "-Dspring.profiles.active=batch", "-jar", "batch-image.jar"]
