# Build stage: 소스 코드를 빌드하는 단계
FROM amazoncorretto:21-alpine-jdk AS build

WORKDIR /home/gradle/src

# 소스 코드를 컨테이너로 복사
COPY . .

# Gradle을 이용하여 module-presentation 모듈만 빌드
RUN ./gradlew :module-presentation:build

# Run stage: 최종 경량 이미지를 생성하는 단계
FROM optimoz/openjre-21.0.3:0.4

WORKDIR /app

COPY --from=build /home/gradle/src/module-presentation/build/libs/module-presentation.jar /app/appu.jar

CMD ["java", "-Djava.net.preferIPv4Stack=true", "-Duser.timezone=Asia/Seoul", "-Dspring.profiles.active=prod", "-jar", "appu.jar"]