pipeline {
    agent any
    tools {
        gradle 'gradle'
        jdk("JDK 21")
    }
    triggers {
        githubPush()
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }
    environment {
        docker_usr = credentials('DOCKERHUB_CREDENTIALS_USR')
        docker_psw = credentials('DOCKERHUB_CREDENTIALS_PSW')
        repository = credentials('DOCKERHUB_REPOSITORY')
        TARGET_HOST = credentials('REMOTE_SERVER_ADDR')
        dockerImage = ''
    }
    stages {
        stage('저장소 복제') {
            steps {
                git branch: 'main', credentialsId: 'GITHUB_ACCESS_TOKEN', url: 'https://github.com/depromeet/Swimie-server'
            }
        }

        stage('빌드') {
            steps {
                sh 'chmod u+w ./module-presentation/src/main/resources/'
                sh 'chmod +x ./gradlew'
            }
        }

        stage('Docker 이미지 빌드') {
            steps {
                script {
                    dockerImage = docker.build(repository + ":latest", "-f ./scripts/Dockerfile-prod .")
                }
            }
        }

        stage('Dockerhub 로그인') {
            steps {
                sh 'echo $docker_psw | docker login -u $docker_usr --password-stdin'
            }
        }

        stage('Dockerhub에 Push') {
            steps {
                sh 'docker push ${repository}:latest'
            }
        }

        stage('원격 서버에 접속하여 deploy 스크립트 실행') {
            steps {
                sh "scp -i ~/.ssh/id_rsa ~/application-secret.properties ${TARGET_HOST}:~/"
                sh "scp -i ~/.ssh/id_rsa ./scripts/shell/deploy.sh ${TARGET_HOST}:~/"
                script {
                    def remoteCommands = """
                        cd ~ &&
                        ./deploy.sh
                    """

                    sshagent (credentials: ['jenkins-ssh']) {
                        sh "ssh ${TARGET_HOST} '${remoteCommands}'"
                    }
                }
            }
        }
    }
}