name: Github Actions CI/CD flow

on:
  push:
    branches: ["develop"]

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USR }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKERHUB_REPO }}
  HOST_USER: ${{secrets.HOST_USER}} # ec2 username
  TARGET_HOST: ${{ secrets.TARGET_HOST }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE: ${{ secrets.AWS_ROLE_ARN }} # AWS 보안 그룹 접근 Role
  AWS_SG_ID: ${{ secrets.AWS_SG_ID }} # ec2 보안 그룹 ID

permissions:
  id-token: write

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx # docker multiplatform
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./scripts/Dockerfile-prod
          push: true
          tags: ${{ env.DOCKER_REPO }}:latest

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Github Action IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Add Github Actions IP to SG # github actions 의  IP를 SG 에 추가하여 접근 가능하게끔 설정
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ env.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Send deploy.sh to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.TARGET_HOST }}
          username: ${{ env.EC2_SSH_USER }}
          key: ${{ env.PRIVATE_KEY }}
          source: "./scripts/shell/deploy.sh" # 배포 스크립트 위치
          target: "/home/ec2-user"
          strip_components: 2 # 숫자만큼 source의 선행 경로 제거
          overwrite: true


      - name: Docker Image Pull and Container run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_SSH_USER }}
          key: ${{ env.PRIVATE_KEY }}
          script: |
            cd /home/ec2-user
            chmod +x deploy.sh
            ./deploy.sh

      - name: Remove Github Action IP from SG
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ env.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

